In [15]:
import tensorflow as tf

In [16]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34, 31]

In [17]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [18]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [19]:
 for sales in tf_dataset.take(3):
    print(sales)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-108, shape=(), dtype=int32)


In [20]:
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [21]:
tf_dataset = tf_dataset.map(lambda x: x*72)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2232
2304
2448
2232


In [22]:
tf_dataset = tf_dataset.shuffle(3)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2304
2232
2232
2448


In [23]:
tf_dataset = tf_dataset.batch(3)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[2232 1584 1512]
[2448 2304 2232]


In [26]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34, 31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(3).batch(3)

for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1584 2232 2304]
[1512 2232 2448]
